### ISSUE TITLE
Something wrong with pars_args()

### ISSUE THREAD

**Issue by XGoldenEggX** [webfp/tor-browser-selenium#100]
Using [this](https://github.com/webfp/tor-browser-selenium/blob/master/examples/check_tpo.py) example, I found a problem in def main()
```
def main():
    desc = "Visit check.torproject.org website"
    parser = ArgumentParser(description=desc)
    parser.add_argument('TBB_PATH')
    args = parser.parse_args()
    visit(args.tbb_path)
```
In line `args = parser.parse_args()` I got an error: 
> the following arguments are required: TBB_PATH

in py3.4, and
>error: too few arguments

in py2.7

If I try debugging step by step it raise:
> args = parser.parse_args()
>        ^
>SyntaxError: invalid syntax

and
>SystemExit: 2

TBB_PATH writed to environment variables
OS: Win10

**Comment by gunesacar** [comment]
`argparse` expects you to pass TBB path as a command line argument. For instance:
`python check_tpo.py  ~/tor-browser_en-US/`

Let me also say that tbselenium is not tested on Windows. If you make it work let me know, otherwise try running it on a Linux VM in your Windows box.
