### ISSUE TITLE
Invalid Firefox binary

### ISSUE THREAD

**Issue by Lukinnno** [webfp/tor-browser-selenium#101]
Hi,
could you please give me an example of correct "tbb_fx_binary_path" for windows?
I have this error: 
Traceback (most recent call last):
  File "C:/Python36/Moje/webTest/Tor2.py", line 10, in <module>
    with TorBrowserDriver("I:\\Tor\\Tor Browser\\") as driver:
  File "C:\Python36\lib\site-packages\tbselenium\tbdriver.py", line 44, in __init__
    tbb_profile_path, tor_data_dir)
  File "C:\Python36\lib\site-packages\tbselenium\tbdriver.py", line 124, in setup_tbb_paths
    % tbb_fx_binary_path)
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary I:\Tor\Tor Browser\Browser\firefox

**Comment by DKanarsky** [comment]
Had the same issue. You should change tbselenium.common.DEFAULT_TBB_FX_BINARY_PATH value to join('Browser', 'firefox.exe'). Now it is:  join('Browser', 'firefox') and the code isfile("...\Browser\firefox") returns False, but it is a file, not directory and must returns True.

**Comment by gunesacar** [comment]
Windows is not supported at the moment.

**Comment by f-tepel** [comment]
Did you manage to fix it @Crisfon6 ?
