### ISSUE TITLE
Question - Run selenium tor with remote web driver (selenium grid)

### ISSUE THREAD

**Issue by edesantis** [webfp/tor-browser-selenium#102]
**Question**

Is there any possibility of running Tor using remote web driver? like:

`var remoteWebDriver = new RemoteWebDriver(DesidedCapabilities.Tor());`

**Comment by gunesacar** [comment]
Assuming you mean _tor browser selenium_ by Tor, I don't know. Feel free to experiment yourself and share your findings with the others.
