### ISSUE TITLE
TBB path issue

### ISSUE THREAD

**Issue by DanailKazakov** [webfp/tor-browser-selenium#104]
I'm having some issues with the basic usage path if someone can assist.

from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/path/to/TorBrowserBundle/") as driver:
    driver.get('https://check.torproject.org')

>> /path/to/TorBrowserBundle/ << what should it be exactly.

My TorBrowser is installed in C:\Test software\Tor Browser, I've tried that directory and in addition I've tried "C:\Test software\Tor Browser\Browser" and "C:\Test software\Tor Browser\Browser\firefox.exe". Please clarify this part.

**Comment by gunesacar** [comment]
Unfortunately, Windows is not supported at the moment.
