### ISSUE TITLE
tbselenium not working with Tor Browser 8.0

### ISSUE THREAD

**Issue by alexgonca** [webfp/tor-browser-selenium#105]
I have tried running my scripts with Tor Browser version 8.0 on Lubuntu 16.04:
https://www.torproject.org/dist/torbrowser/8.0/tor-browser-linux64-8.0_en-US.tar.xz

The browser is working fine when I start it from command line.
When I start it via tbselenium, it does not connect to the Tor process and issues the following error message:
"The proxy server is refusing connections".

The script works fine when I downgrade Tor Browser to version 7.5.6.

**Comment by gunesacar** [comment]
Thanks for reporting. Indeed, upgrading to v8 [broke many tests](https://travis-ci.org/gunesacar/tor-browser-selenium/jobs/425081761).

In the meantime, please update `geckodriver` and `selenium`to latest if you happen to have out of date versions. As you can see from the [Travis test results](https://travis-ci.org/gunesacar/tor-browser-selenium/jobs/425081761), a lot of tests actually pass.

**Comment by alexgonca** [comment]
I am using the latest selenium version... but I thought we had to use geckodriver v0.17.0 [according to the installation instructions](https://github.com/webfp/tor-browser-selenium#installation). Is that not the case anymore?

**Comment by gunesacar** [comment]
> I am using the latest selenium version... but I thought we had to use geckodriver v0.17.0 [according to the installation instructions](https://github.com/webfp/tor-browser-selenium#installation). Is that not the case anymore?

It won't be the case any more with TB 8.0. Will be updated to the latest `geckodriver` version.

I just checked: `tbselenium` & TB 8.0 work together nicely if you use external `tor` process, such as 1) system `tor` via `tor_cfg=cm.USE_RUNNING_TOR` or 2) `stem` (see `example/stem_simple.py` example).

**Comment by gunesacar** [comment]
This [example](https://github.com/webfp/tor-browser-selenium/blob/tbbv8/examples/check_tpo_using_system_tor.py) works for me with Tor Browser v8.0, `geckodriver` v0.21.0 and `selenium` v3.12.0

**Comment by elfelround** [comment]
8.0.4 tor & recommended gecko 0.17 also gives me this issue

**Comment by redshiftzero** [comment]
Given the [test failures](https://travis-ci.org/gunesacar/tor-browser-selenium/jobs/425081761), we should expect limited functionality (e.g. `JSDisableTest.test_disable_js` is failing) using an external tor process no?

**Comment by blackdolphin65** [comment]
I am facing the same problem, I also tried to install Selenium 3.3 as you have in the requirements but it says that selenium 3.3 is incompatible with tbselenium. Here you have the log from the installation of selenium 3.3: https://0bin.net/paste/ykQ0JFwr-qO+L6xR#Wx+h6tebNX+V-Wu/+dNOx55IiLIEyHkyp9f3l9T2pFP Let me know if I can do something else to fix this issue for me and other people who may face the same problem
