### ISSUE TITLE
Running on mac?

### ISSUE THREAD

**Issue by gg4u** [webfp/tor-browser-selenium#106]
Hi, 

I read mac iOS is not supported, but maybe it may work by pointing the driver to the bundle of mac (locate TOR in app directory, and right click on "Show package content").

Though, I am getting ` TBB path is not a directory` error and don't know if because I have TOR 8.0.2 or other matter.

```
Traceback (most recent call last):
  File "check_tpo_using_system_tor.py", line 32, in <module>
    main()
  File "check_tpo_using_system_tor.py", line 28, in main
    visit(args.tbb_path)
  File "check_tpo_using_system_tor.py", line 10, in visit
    with TorBrowserDriver(tbb_dir, tor_cfg=cm.USE_RUNNING_TOR) as driver:
  File "/Users/gg4u/Sites/casafari/venv3/lib/python3.6/site-packages/tbselenium/tbdriver.py", line 44, in __init__
    tbb_profile_path, tor_data_dir)
  File "/Users/gg4u/Sites/casafari/venv3/lib/python3.6/site-packages/tbselenium/tbdriver.py", line 119, in setup_tbb_paths
    % tbb_path)
tbselenium.exceptions.TBDriverPathError: TBB path is not a directory /Applications/Tor Browser.app/Contents/MacOS/firefox
```

I pointed the tbb_path to the TOR firefox of the bundle.

I also tried to point it to the geckodriver , which is installed in the same directory (I m using virtual environment).

I also tried to see if it was problem of escaping space within unix folder:
```
/Applications/Tor Browser.app/Contents/MacOS/firefox
/Applications/Tor\ Browser.app/Contents/MacOS/firefox
```

None of them works.

Is it because really no support on Mac or may this way get selenium work behind tor ?

**Comment by gunesacar** [comment]
You may try replacing the [paths for Linux](https://github.com/webfp/tor-browser-selenium/blob/master/tbselenium/common.py#L6-L16) with the paths you find in TBB for Mac.

It may be possible to have tbselenium working with Mac, but I won't be able to offer support for that.

**Comment by slorenzo** [comment]
I'm wondering if anyone has this configuration to share?

**Comment by maximilianromer** [comment]
I built it @saeta-eth 😁 https://github.com/maximilianromer/tbselenium-macos
