### ISSUE TITLE
invalid firefox binary

### ISSUE THREAD

**Issue by arnodumora** [webfp/tor-browser-selenium#107]
Hello,

I'm trying to lunch a webdriver as said in your readme. However I always have this error:

`driver = TorBrowserDriver(tbpath, tbb_logfile_path='test.log')
---------------------------------------------------------------------------
TBDriverPathError                         Traceback (most recent call last)
<ipython-input-4-c4302d6b5a8b> in <module>()
driver = TorBrowserDriver(tbpath, tbb_logfile_path='test.log')

~/MyGit/web-scraping/scrap2/venv/lib/python3.6/site-packages/tbselenium/tbdriver.py in __init__(self, tbb_path, tor_cfg, tbb_fx_binary_path, tbb_profile_path, tbb_logfile_path, tor_data_dir, pref_dict, socks_port, control_port, extensions, default_bridge_type, capabilities)
 self.tor_cfg = tor_cfg
self.setup_tbb_paths(tbb_path, tbb_fx_binary_path,
                             tbb_profile_path, tor_data_dir)
self.profile = webdriver.FirefoxProfile(self.tbb_profile_path)
self.install_extensions(extensions)

~/MyGit/web-scraping/scrap2/venv/lib/python3.6/site-packages/tbselenium/tbdriver.py in setup_tbb_paths(self, tbb_path, tbb_fx_binary_path, tbb_profile_path, tor_data_dir)
if not isfile(tbb_fx_binary_path):
            raise TBDriverPathError("Invalid Firefox binary %s"
                                     % tbb_fx_binary_path)
if not isdir(tbb_profile_path):
raise TBDriverPathError("Invalid Firefox profile dir %s"

TBDriverPathError: Invalid Firefox binary /home/arnaud/MyGit/web-scraping/scrap2/tor-browser_en-US/Browser/firefox

Could someone help me?

**Comment by hasanparasteh** [comment]
same problem 
`tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary C:\Users\Acount\Desktop\Tor Browser\Browser\Browser\firefox`

**Comment by gunesacar** [comment]
> ~/MyGit/web-scraping/scrap2/venv/lib/python3.6/site-packages/tbselenium/tbdriver.py in setup_tbb_paths(self, tbb_path, tbb_fx_binary_path, tbb_profile_path, tor_data_dir)
if not isfile(tbb_fx_binary_path):
raise TBDriverPathError("Invalid Firefox binary %s"
% tbb_fx_binary_path)
if not isdir(tbb_profile_path):
raise TBDriverPathError("Invalid Firefox profile dir %s"

`TBDriverPathError` means that `tbselenium` cannot find the Firefox binary on this path. 
Make sure you pass the right `tbb_path`, in your case it would be:
`/home/arnaud/MyGit/web-scraping/scrap2/tor-browser_en-US/`

> same problem
> `tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary C:\Users\Acount\Desktop\Tor Browser\Browser\Browser\firefox`

Windows is not supported.
