### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=proxyConnectFailure&u

### ISSUE THREAD

**Issue by AmirMonfared** [webfp/tor-browser-selenium#108]
Hi,
when tor tries to open any website, i got this error:
"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=proxyConnectFailure&u"".

can you help me?
thank you

**Comment by gunesacar** [comment]
That means Tor Browser cannot connect to the local proxy. How do you use the library? Which version of the TBB do you use? Which constructor parameters do you set? It's not possible to help without all these details.

**Comment by mrpew** [comment]
I get the same problem w/ 

`from tbselenium.tbdriver import TorBrowserDriver`
`with TorBrowserDriver("/path/to/tbb/") as driver:`
`    driver.get('https://www.google.com/')`

Using Tor Browser 8.0.4, geckodriver 0.23.0

Using

**Comment by rjunior8** [comment]
from tbselenium.tbdriver import TorBrowserDriver
import tbselenium.common as cm


with TorBrowserDriver("/home/user/tor-browser_en-US/", tor_cfg=cm.USE_RUNNING_TOR) as driver:
  driver.get("https://github.com")
