### ISSUE TITLE
get(url) is synchronous when shouldn't

### ISSUE THREAD

**Issue by michelecampobasso** [webfp/tor-browser-selenium#109]
The function `load_url(url,timeout,wait)` says in its description that the timeout allows to don't return immediately the function but to wait for the expiration of the timeout.
Nonetheless, the `get(url)` function inside of it doesn't return until the DOM is completely loaded, resulting the `load_url(url,timeout,wait)` in an extra timeout without effect. 

The synchronous behavior of `get(url)` introduces a problem: whereas `tor` changes circuit for any reason while `torbrowser` is loading a page, it cases the loading to hang indefinitely. 

Failing both with geckodriver 0.17.0 and 0.23.0, TB 8.0.2 and Selenium 3.141.0.

**Comment by gunesacar** [comment]
Sorry, I'm confused: `tbselenium` doesn't have function with the signature you mention: `load_url(url,timeout,wait)`

**Comment by michelecampobasso** [comment]
Sorry, I wrote the arguments improperly. The correct signature is: `def load_url(self, url, wait_on_page=0, wait_for_page_body=False)`. It is found in `tbselenium/tbdriver.py`

**Comment by michelecampobasso** [comment]
My bad. I didn't realize that is handled by Selenium directly. 

For documentation purposes, I report here that Selenium WebDriver exposes a function `set_page_load_timeout(timeout_secs)` that allows to interrupt loading of the page raising a `TimeoutException`.

Thanks for your support.
