### ISSUE TITLE
Question-How should I use ‘tor-browser-selenium’ for my own obf4-bridge ?

### ISSUE THREAD

**Issue by CatAndCoffee** [webfp/tor-browser-selenium#111]
I want to use tor-browser-selenium to lauch the TBB with my own obfs4 bridge. What should i do?

**Comment by gunesacar** [comment]
You need to find and set the relevant preference with the details of your bridge. The pref name should be something like this: `extensions.torlauncher.default_bridge.obfs4.1` depending on the bridge type.

You may set new prefs by passing them in the  `pref_dict` during initialization.
