### ISSUE TITLE
TBDriverPortError: SOCKS port 9050 is not listening

### ISSUE THREAD

**Issue by sursu** [webfp/tor-browser-selenium#116]
I try to run:

```python
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/home/user/Downloads/tor-browser_en-US") as driver:
    driver.get('https://check.torproject.org')
```
but I get the error:

`TBDriverPortError: SOCKS port 9050 is not listening`

What's to be done?

---

I had to mention that I am on Ubuntu 18.04.

Apparently one needs to install tor via `sudo apt install tor`. Installing a binary version does not work.
Weird though, the specified path needs to be to the binary version.

**Comment by gunesacar** [comment]
Thanks for sorting this out.

By default tbselenium uses _system_ tor, which uses SOCKS port 9050 by default: https://github.com/webfp/tor-browser-selenium/blob/master/tbselenium/tbdriver.py#L30

I'll make sure I clarify this in the README and troubleshooting.

**Comment by harunurkst** [comment]
I am also facing the same issue. Which port should I use as  socks_port ?
