### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by SaltOfTheFlame** [webfp/tor-browser-selenium#119]
There are several problems while running on windows...

**Comment by gunesacar** [comment]
Windows is not supported.

**Comment by CodeCrusha** [comment]
0

I just modified some files of webfp/tor-browser-selenium and it works now under windows - yipie. The only thing is, a tor-browser has to be started already.

After pip installing it, under C:\XXX\PythonXXX\Lib\site-packages\tbselenium modify these files:

common.py
utils.py
tbdriver.py
In common.py modify:

DEFAULT_TBB_FX_BINARY_PATH from "firefox" to "firefox.exe"
DEFAULT_TOR_BINARY_PATH "tor" to "tor.exe"
In tbdriver.py modify:

"socks_port = cm.STEM_SOCKS_PORT" to "socks_port = cm.TBB_SOCKS_PORT"
In utils.py modify:

in "launch_tbb_tor_with_stem" remove the whole return
Code which will work under Windows (with already opened Tor Browser):

```
from tbselenium.tbdriver import TorBrowserDriver
import tbselenium.common as cm
from tbselenium.utils import launch_tbb_tor_with_stem

launch_tbb_tor_with_stem("C:\\Users\\CodeCrusha\\Desktop\\Tor Browser") # I think you can remove this, but maybe some future usages need that 
with TorBrowserDriver("C:\\Users\\CodeCrusha\\Desktop\\Tor Browser", tor_cfg=cm.USE_STEM) as driver:
    driver.load_url("https://check.torproject.org", wait_on_page=3, wait_for_page_body=True)
    print(driver.find_element_by("h1.on").text)
    print(driver.find_element_by(".content > p").text)
```

**Comment by amoh-godwin** [comment]
@Develobba you are such a life saver

**Comment by amoh-godwin** [comment]
@gunesacar I was hoping I could get a PR accepted with @Develobba modified files for Windows users. Thank you.
