### ISSUE TITLE
Get IP address of entry node

### ISSUE THREAD

**Issue by ThalesMilesius** [webfp/tor-browser-selenium#120]
When sequentially loading a list of URLs, how would I collect the entry nodes' IP addresses that were actually used?

Looking at the following example, what changes would be necessary in order to have the file `ips.txt` contain the IP addresses of the entry nodes that were actually (not just potentially as in "available in a built circuit") used to retrieve the web pages?

~~~ python
import tbselenium.common as cm
from tbselenium.tbdriver import TorBrowserDriver
from tbselenium.utils import launch_tbb_tor_with_stem


tbb_dir = "/home/user/tor-browser_en-US/"
urls = ["https://www.example.com",
        "https://www.bbc.com/",
        "https://edition.cnn.com/"]
ips = open('ips.txt', 'w')

tor_process = launch_tbb_tor_with_stem(tbb_path=tbb_dir)
with TorBrowserDriver(tbb_dir, tor_cfg=cm.USE_STEM) as driver:
    for url in urls:
        driver.load_url(url)

tor_process.kill()
ips.close()
~~~

I am aware that one can use

~~~ python
with stem.control.Controller.from_port(port=cm.STEM_CONTROL_PORT) as controller: 
    controller.authenticate()                                                    
                                                                                 
    for circ in sorted(controller.get_circuits()):                               
        if circ.status != CircStatus.BUILT:                                      
            continue                                                             
        entry_fingerprint = circ.path[0][0]                                      
        entry_descriptor = controller.get_network_status(entry_fingerprint, None)
        ips.write(str(entry_descriptor.address + '\n'))                                         
~~~

to get the entry nodes' IP addresses from the built circuits at a given time. However, AFAIK Tor circuits including entry nodes can change over time.

In case there's no solution to my original question such that I have to go with the latter code snippet: Do I have to collect the entry IPs every time right before visiting a web page just to be sure I don't miss an IP because the circuits change in between the loading of pages? What if the available entry nodes change right between collecting the entry IPs and loading a page, such that `ips.txt` does not contain the IP that was actually used?

I'm sorry if I missed the answer to my question in this repository or the Stem docs.

**Comment by gunesacar** [comment]
Sorry for the delay in responding.

I can't see how this library can be used to achieve that. You may try hacking the torbutton extension or parsing the Tor debug logs. You should be able see number of cells sent over each circuit if you enable the debug logs.

You may still need to combine the debug logs with your "option 2", but I'd use an event listener to get notified whenever a circuit is constructed instead of polling for circuits. Stem supports even listeners.

**Comment by ThalesMilesius** [comment]
Thanks for the tip!
