### ISSUE TITLE
Supporting Snowflake Bridge?

### ISSUE THREAD

**Issue by kylmac** [webfp/tor-browser-selenium#122]
Is there a way to use tbselenium using the snowflake bridge? It is not currently listed as a supported bridge.

**Comment by gunesacar** [comment]
Theoretically, you should be able to set a custom bridge by passing related preferences in `pref_dict`(similar to [this](https://github.com/webfp/tor-browser-selenium/blob/7946c2172f569ebcc191f0eefbc93c0c38d67e63/tbselenium/tbdriver.py#L209-L210)) ), but I could not make this work with the latest stable or alpha.

**Comment by kylmac** [comment]
In the example you linked, does this mean initializing the driver list this:
`TorBrowserDriver(tbpath, tbb_logfile_path='test.log', 
            default_bridge_type='snowflake 0.0.3.0:1 url=https://snowflake-broker.azureedge.net/ front=ajax.aspnetcdn.com ice=stun:stun.l.google.com:19302 max=3')`

of like this:

`TorBrowserDriver(tbpath, tbb_logfile_path='test.log', 
           pref_dict={'snowflake 0.0.3.0:1 url=https://snowflake-broker.azureedge.net/ front=ajax.aspnetcdn.com ice=stun:stun.l.google.com:19302 max=3')}`

**Comment by gunesacar** [comment]
First, it looks like you need to use an alpha version of the Tor Browser.
 `2018-11-30: Snowflake is included in ​alpha releases of Tor Browser for GNU/Linux and macOS. Not Windows yet.`  (https://trac.torproject.org/projects/tor/wiki/doc/Snowflake)

That means, you just need to pass `default_bridge_type=snowflake`; something like the following:
`TorBrowserDriver(tbpath, tbb_logfile_path='test.log', default_bridge_type='snowflake')`

**Comment by kylmac** [comment]
Gotcha, I'm running bridge.py from the examples directory and passing `default_bridge_type=snowflake`. The error I see here is: `in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession`

**Comment by gunesacar** [comment]
I'd use Wireshark to check the IPs Tor Browser is talking to. Then see if the IP belongs to a guard node or not.

You can also try to detect the WebRTC traffic in the captures.
See also, https://arxiv.org/pdf/1605.08805.pdf

**Comment by kylmac** [comment]
When running the bridge example file, it seems to open up a successful tor browser, but it hangs on TorBrowserDriver(tbb_dir) and doesn't execute anything after that. That is when I see the above message. Any idea why this is the case?
