### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by muhendis80** [webfp/tor-browser-selenium#123]
Merhaba, Gunes Acar ismini okuyunca ilk önce fark edemedim.. ama sonra Turk ismi olduğunu fark edince çok mutlu oldum.. bu tip icraatlerde Turkleri görmek mümkün değil.. Eğer uygunsa web scrabbing ile takıldığım bir konu var.. buradan yazmak istemiyorum, daha özel bir iletişime nasıl geçebilirim.. yasindemircioglu@hotmail.com

**Comment by gunesacar** [comment]
@muhendis80 ne yazik ki proje ile ilgili sorunlara bile zor zaman buluyorum. Ama bu kutuphane ile ilgili sorununuz olursa "issue" acip sormaktan cekinmeyin.
