### ISSUE TITLE
Can I use this with a client transport plugin?

### ISSUE THREAD

**Issue by websitefingerprinting** [webfp/tor-browser-selenium#124]
Hi! I just wonder whether this crawler can be used with a client transport plugin?  
I use my own plugin in my Torrc file:

UseBridges 1    
Bridge obfs4 x.x.x.x:35000 cert=xxx iat-mode=0
ClientTransportPlugin obfs4 exec /home/aaron/obfs4/obfs4proxy/obfs4proxy

Thank you very much!

**Comment by gunesacar** [comment]
Sure, you should just add the above lines to the `torrc` in `tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc`.

I'd then use Wireshark to verify that tor is talking to the bridge, but not to the guard.

**Comment by websitefingerprinting** [comment]
@gunesacar Thank you for your reply!  But I think the `torrc` you mentioned was not called when I use `tor-browser-selenium`. Instead, I tried the following: 
1. I opened Bridge service on my server: `tor -f my-bridge-torrc`
2. I open Tor service on my client: `tor -f my-client-torrc`
3. I then run `python3 examples/headless.py` and it worked. 

I saw the traffic on my bridge side so the browser driver was talking to bridge. I feel very surprised about that. 
Do you have any idea why `tor-browser-selenium driver` automatically use the Tor I launched in the terminal? 

Thank you!

**Comment by gunesacar** [comment]
Clo
