### ISSUE TITLE
Issue with running TB-selenium

### ISSUE THREAD

**Issue by harry0987** [webfp/tor-browser-selenium#125]
I installed tbselenium on linux using pip but when i am getting following port error:
  File "/home/user/.local/lib/python2.7/site-packages/tbselenium/tbdriver.py", line 88, in init_ports
    % socks_port)
TBDriverPortError: SOCKS port 9050 is not listening

I am using tbslelenium with below code:

import unittest
from time import sleep
from tbselenium.tbdriver import TorBrowserDriver

class TestSite(unittest.TestCase):
    def setUp(self):
        # Point the path to the tor-browser_en-US directory in your system
        tbpath = '/home/user/Downloads/tor-browser_en-US/'
        self.driver = TorBrowserDriver(tbpath, tbb_logfile_path='test.log')
        self.url = "https://check.torproject.org"

    def tearDown(self):
        # We want the browser to close at the end of each test.
        self.driver.close()

    def test_available(self):
        self.driver.load_url(self.url)
        # Find the element for success
        element = self.driver.find_element_by_class_name('on')
        self.assertEqual(str.strip(element.text),
                         "Congratulations. This browser is configured to use Tor.")
        sleep(2)  # So that we can see the page

if __name__ == '__main__':
    unittest.main()
~                         

Please suggest.

**Comment by gunesacar** [comment]
Sorry for the late response. This means `tor` is not listening on port 9050. You can either install it (e.g. by `apt install tor`) or follow [this example](https://github.com/webfp/tor-browser-selenium/blob/master/examples/stem_simple.py) to start `tor` via `stem` yourself.

**Comment by gunesacar** [comment]
I updated the README to clarify requirements wrt. to system `tor`
