### ISSUE TITLE
How to specify user agent?

### ISSUE THREAD

**Issue by davidlee321** [webfp/tor-browser-selenium#127]
Good day all. How to specify user agent?

something like:

```python
my_user_agent = " .... "
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/home/d/Downloads/tor-browser_en-US/", user_agent=my_user_agent) as driver:
    driver.get('https://check.torproject.org')
```

Or is resist fingerprinting enabled in tor browser by default? i assume that randomizing user agent is part of resisting fingerprinting. 

Also, while on the topic of privacy, is there a way to programatically change exit relay node?

**Comment by goggoloid** [comment]
did you ever figure out how to specify user agent?

**Comment by davidlee321** [comment]
nope :(

**Comment by gunesacar** [comment]
Sorry for the late response. First, a warning: randomizing user agent will make your Tor browser  unique and therefore is not recommended.

> Or is resist fingerprinting enabled in tor browser by default? i assume that randomizing user agent is part of resisting fingerprinting.

`resistFingerprinting` is enabled in the Tor browser, but [it doesn't randomize the user agent](https://wiki.mozilla.org/Security/Fingerprinting)

But, it disables user agent overrides:
https://bugzilla.mozilla.org/show_bug.cgi?id=1489903

So, `resistFingerprinting` needs to be disabled to override the user agent.

Another warning: do not disable `resistFingerprinting` unless you know what you are doing.

With all these warnings, here's the code to initialize tbselenium with a spoofed user agent:
```
    NEW_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
    with TorBrowserDriver(tbb_dir,
      pref_dict={"privacy.resistFingerprinting": False,
                  "general.useragent.override": NEW_UA}) as driver:
```

The key is to use the `pref_dict` argument to change Firefox's preferences - which you normally edit on `about:config`.

**Comment by gunesacar** [comment]
> Also, while on the topic of privacy, is there a way to programatically change exit relay node?

You can use Stem to do that: https://stem.torproject.org/tutorials/to_russia_with_love.html#custom-path-selection

And tbselenium works nicely with Stem. See the examples.

**Comment by goggoloid** [comment]
> Sorry for the late response. First, a warning: randomizing user agent will make your Tor browser unique and therefore is not recommended.
> 

Maybe a dumb question but; is this still true if you rotate multiple user agents?
