### ISSUE TITLE
New tor circuit

### ISSUE THREAD

**Issue by SergioShz** [webfp/tor-browser-selenium#130]
Hi guys, amazing work here!

I was wondering, is there any way to set a new circuit?

I looked for some method such as `new_circuit` or something like that but didn't find anything similar.

Thank you very much!

**Comment by gunesacar** [comment]
Hi,
You can use [Stem](https://stem.torproject.org/index.html) to create new circuits.
Follow the example code [here](https://github.com/webfp/tor-browser-selenium/blob/master/examples/stem_adv.py) to use tbselenium in combination with Stem.
