### ISSUE TITLE
stem package dependency not well-documented

### ISSUE THREAD

**Issue by randomdude999** [webfp/tor-browser-selenium#131]
The README doesn't mention that you need to install the `stem` package from PyPI manually in order to use `launch_tbb_with_stem`. This may seem obvious, but the error messages are very vague when this package is missing (about an undefined function `launch_tor_with_config`, because that was imported from stem while ignoring exceptions). Either the error message should be improved, or the README should mention the dependency.

**Comment by gunesacar** [comment]
Thanks for reporting. Clarified in the README.
