### ISSUE TITLE
filenotfound Applicationlocation/Browser

### ISSUE THREAD

**Issue by pedrolopes101** [webfp/tor-browser-selenium#141]
I downloaded the library and ran it and on my first try I got the error:
Filenotfound Applicationlocation/Browser doesn't exist. For this I went to the directory and made the folder.
This made that the application worked perfectly.
But for my application I need to keep remaking Tor instances over and over again.
So now I have the issue everytime I loop through the code I get Applicationlocation/Browser/Browser does't exist. If I make the folder on next loop I get: Applicationlocation/Browser/Browser/Browser. And so forth. Is there any way to fix this?

My code looks like the following
```
def startselerium ():   
        try:
            driver= TorBrowserDriver(executable_path="C:\\Python39\\geckodriver.exe", tbb_fx_binary_path="D:\\Tor Browser\\Browser\\firefox.exe", tbb_profile_path="D:\\Tor Browser\\Browser\\TorBrowser\\Data\\Browser",headless=True)
            driver.get("https://website.com/")     
            driver.close()
        except Exception as e:
            logging.error(msg='Error for user ', exc_info=e)

```

The problem is also mentioned on the reply of this stackoverflow post I had made when I first started working with tbselerium
[Stackoverflowpost](https://stackoverflow.com/questions/65382324/opening-tor-in-selenium-giving-error-when-opening-browser/65382715#65382715)

**Comment by gunesacar** [comment]
Hi @pedrolopes101, 
Unfortunately, Windows is not supported at the moment. You may try running a Linux virtual machine or subsystem on Windows.
