### ISSUE TITLE
Always getting error "No such file or directory: 'webdriver-py-profilecopy'"

### ISSUE THREAD

**Issue by l4zygreed** [webfp/tor-browser-selenium#142]
tbselenium 0.5.3 (or 0.5.2)
selenium 3.141.0 (tried some other >3 versions)
tor browser 10.0.7 (linux64)

Code worked for some time, but now after launch getting error like `No such file or directory: '/tmp/tmpgpl9c40g/webdriver-py-profilecopy'`
Running code as root and directory actually exists..

**Comment by gunesacar** [comment]
@l4zygreed thank you for reporting.

Unfortunately, this is a generic Selenium error, so it's hard to say what's going on just based on this message.

Some questions that may help understand the problem:
- Do you see a `geckodriver.log` in the profile directory? You may search for unexpected error messages in that log. **Please avoid sharing it publicly**.
- Is this a windowless (e.g. over SSH) session? If so, do you use XVFB or similar virtual display servers?
- Does the same code work on other computers?
- Do the [examples](https://github.com/webfp/tor-browser-selenium/tree/master/examples) work?
