### ISSUE TITLE
Bug in constructor?

### ISSUE THREAD

**Issue by ikucan** [webfp/tor-browser-selenium#147]
Is the intent to either provide the tbb_path or both ffx exe and profile paths?

if so the logic is wrong? if I chose the latter then the line 131 has little chance of generating correct path:

```131: self.tbb_path = abspath(tbb_path)```

If correct please let me know and I can submit a fix. For the second case, one could assume the ```self.tbb_browser_dir``` to simply be a parent of the ffx executable?

**Comment by gunesacar** [comment]
@ikucan, thanks for the report.
You can see that the CI tests on Travis pass with the current constructor.
https://travis-ci.org/github/webfp/tor-browser-selenium/builds/764770107

I see that you mentioned "exe"; unfortunately tor-browser-selenium doesn't support Windows at the moment.


> Is the intent to either provide the tbb_path or both ffx exe and profile paths?

Yes
