### ISSUE TITLE
Tor Browser on Android

### ISSUE THREAD

**Issue by ahmadmasalhags** [webfp/tor-browser-selenium#151]
Is it possible to use this to run Tor Browser App on an Android device?
I tried by adding the device's udid and Tor app package to the capabilities but it didn't work.

Or is there a way to use this as a web driver context when using Appium?

**Comment by gunesacar** [comment]
Hello @ahmadmasalhags ,
Unfortunately no. This library doesn't support Tor Browser for Android.

If you are interested in submitting a pull request, I'll be happy to review and give feedback.

If you are only interested visiting mobile versions of websites over Tor, emulating a mobile device can be a quick and dirty solution. See answers to [this SO question](https://stackoverflow.com/questions/46771456/how-to-automate-firefox-mobile-with-selenium/):

> Or is there a way to use this as a web driver context when using Appium?

Not that I know of.
