### ISSUE TITLE
Is it possible to capture HAR requests for every URL that we load?

### ISSUE THREAD

**Issue by askumar2903** [webfp/tor-browser-selenium#152]

**Comment by gunesacar** [comment]
Not as is, but you could try installing the [har-export-trigger](https://github.com/firefox-devtools/har-export-trigger) and follow the [instructions](https://github.com/firefox-devtools/har-export-trigger#how-to-use) provided in its README.

**Comment by askumar2903** [comment]
Yeah. Thank you. Tried that. and It Worked :)
