### ISSUE TITLE
Tor browser selenium for window

### ISSUE THREAD

**Issue by nqthai309** [webfp/tor-browser-selenium#153]
How to use tbselenium for windows or something similar,  plssss :(( Thanks

**Comment by gunesacar** [comment]
Unfortunately Windows is not supported at the moment.

**Comment by buddhabas** [comment]
> Why not. Just add ".exe" to all binary vars in this project. All work perfectly ![image](https://user-images.githubusercontent.com/9198186/168108546-35bfe1a3-5286-45ec-95aa-4c0ecda0dd9b.png)

Does it work now? Thanks!

**Comment by AntoineCimino** [comment]
@Mostalk how / do you do this ? 

thanks a lot

**Comment by AntKenan** [comment]
> 

but I don't see any .exe on screenshot you provided. Or am I missing something?

**Comment by RealSting** [comment]
> > 
> 
> but I don't see any .exe on screenshot you provided. Or am I missing something?

Did you try also with "Tor Expert Bundle" in Windows? It works perfectly.
https://www.torproject.org/it/download/tor/

**Comment by AntKenan** [comment]
> > > 
> > 
> > 
> > but I don't see any .exe on screenshot you provided. Or am I missing something?
> 
> Did you try also with "Tor Expert Bundle" in Windows? It works perfectly. https://www.torproject.org/it/download/tor/

actually i figured out what he meant by adding .exe. You need to add .exe inside btselenium lib file, when I did that it worked.
