### ISSUE TITLE
Make sure we load the Firefox libraries from TBB's Browser directory

### ISSUE THREAD

**Issue by gunesacar** [webfp/tor-browser-selenium#16]
We should investigate the issue @fowlslegs mentions in https://github.com/webfp/tor-browser-selenium/issues/10#issuecomment-208663329:

> so now it's failing because certain libraries libxul.so (the main Firefox library) is wanting to load are not present on this minimal image.

We should make sure that TB prefers the Firefox libraries shipped with TBB, not the ones found on the system.

**Comment by fowlslegs** [comment]
That was not quite the issue I brought up in #10 because the libraries I mentioned are not shipped with TBB, but anyway this is a good test if you want to make sure your calls to `os.environ` are working right.

**Comment by gunesacar** [comment]
Ok, now I realize they must be the ones in this commit: https://github.com/freedomofpress/FingerprintSecureDrop/commit/9f57ebe41e10632eb3704ad0e3348f76dc2f59ec

**Comment by fowlslegs** [comment]
Yup.
