### ISSUE TITLE
Error with the new version of selenium or python-selenium

### ISSUE THREAD

**Issue by druzy** [webfp/tor-browser-selenium#187]
With selenium 4.10.0, I have this error : 
`TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'`

Just comment the line n° 100 in tbselenium/tbdriver.py

`super(TorBrowserDriver, self).__init__(`
`            service=tbb_service,`
`            #executable_path=executable_path,`
`            options=self.options,`
`            )`

And the bug is fix.

**Comment by gunesacar** [comment]
Thanks @druzy for the heads up. Fixed in https://github.com/webfp/tor-browser-selenium/commit/0254df106f11d7d8269d2e2c6715ad55073a1aef.

**Comment by druzy** [comment]
You welcome.
