### ISSUE TITLE
Use custom tor build

### ISSUE THREAD

**Issue by f-tepel** [webfp/tor-browser-selenium#191]
Hi,

I compiled my own tor browser because I want to change some settings. Currently I did not change anything but just build the most current branch.

When trying to connect to it with this package I got the error:
```
Traceback (most recent call last):
  File "/home/felix/Documents/selenium/main.py", line 6, in <module>
    tor_process = launch_tbb_tor_with_stem(tbb_path=tbb_dir)
  File "/home/felix/.local/lib/python3.10/site-packages/tbselenium/utils.py", line 85, in launch_tbb_tor_with_stem
    raise StemLaunchError("Invalid Tor binary")
tbselenium.exceptions.StemLaunchError: Invalid Tor binary
```

I know this might not be the right place to ask but I was thinking maybe somebody knows something about this here.

**Comment by gunesacar** [comment]
The error means the `tbselenium` cannot find the `tor` binary in the expected location:
https://github.com/webfp/tor-browser-selenium/blob/ac2d132f76093d7bd17749c293cc4ea4e2899551/tbselenium/utils.py#L81-L85

If you are building Tor Browser yourself, I'd make sure to mirror the directory structure of Tor Browser Bundle.
Alternatively, you can [start tbselenium with system Tor](https://github.com/webfp/tor-browser-selenium#using-with-system-tor), so you don't have to deal with launching it with Stem.
