### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by Berseck20** [webfp/tor-browser-selenium#193]
Hi, i'm getting this error while i try to install tor-selenium

`
pip install tbselenium
Collecting tbselenium
  Using cached tbselenium-0.7.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Usuario\AppData\Local\Temp\pip-install-wjqn843y\tbselenium_3fd7ac2d80c74fce91869ad0c3c94895\setup.py", line 4, in <module>
          long_description = f.read()
                             ^^^^^^^^
        File "D:\python3.11\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2727: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
`

**Comment by gunesacar** [comment]
Unfortunately Windows is not supported. The `tbselenium` package can be installed on Linux (where it's supported) without any problems.
