### ISSUE TITLE
Initialization error with Selenium 4.11

### ISSUE THREAD

**Issue by gunesacar** [webfp/tor-browser-selenium#195]
CI tests are failing with the new selenium 4.11 version:
https://app.travis-ci.com/github/webfp/tor-browser-selenium/jobs/607452192

It's related to the (Firefox) binary location, which we may address by explicitly passing it
```
ERROR: TBDriver init error. Attempt 2 Message: Unable to locate or obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

**Comment by druzy** [comment]
I find a temporary solution.
In tbdriver.py change line 34 : 
`executable_path="geckodriver`
to
`executable_path="/usr/bin/geckodriver`

**Comment by gunesacar** [comment]
Closed in https://github.com/webfp/tor-browser-selenium/commit/8c3fa94a185f5884454e7fc918551dc54b04f60c.`
