### ISSUE TITLE
Help me on Mac gecko driver

### ISSUE THREAD

**Issue by Demidof** [webfp/tor-browser-selenium#196]
Can you tell me how to install it on a mac? I installed tbselenium, but I can't install geckodriver. I ask for help

**Comment by gunesacar** [comment]
Mac is not supported, but you can consider running a Linux VM or getting help on the [Discussions](https://github.com/webfp/tor-browser-selenium/discussions) section.
https://github.com/webfp/tor-browser-selenium#%EF%B8%8F-compatibility
