### ISSUE TITLE
error with selenium 4.11 and driver

### ISSUE THREAD

**Issue by druzy** [webfp/tor-browser-selenium#197]
There is a error with the new selenium. See : [https://github.com/webfp/tor-browser-selenium/issues/195](url)
I find a temporary solution.
In tbdriver.py line 34 change
` executable_path="geckodriver"`
to
` executable_path="/usr/bin/geckodriver"`
And it work and i don't know why.

**Comment by gunesacar** [comment]
Thanks for the report. Starting from version 4.11 Selenium stopped expanding the  `executable_path` initialization  parameter into an absolute path (for `geckodriver`). We now pass the return value of `shutil.which`: https://github.com/webfp/tor-browser-selenium/commit/8c3fa94a185f5884454e7fc918551dc54b04f60c
