### ISSUE TITLE
Invalid firefox binary

### ISSUE THREAD

**Issue by Aphexus** [webfp/tor-browser-selenium#201]
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary

I got a similar result when trying to use the binary directly with selenium without tbselenium(which is what lead me to tbselenium).

I'm not sure if this is an issue with tbselenium, selenium or something else. The binary is exactly what I use to run tor with.

**Comment by ShlomiRex** [comment]
I get this error on macOS aswell:
```
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary /Applications/Tor Browser.app/Browser/firefox
```

**Comment by gunesacar** [comment]
[This error is likely due to unsupported OSes](https://github.com/webfp/tor-browser-selenium#%EF%B8%8F-compatibility)
Please reopen if you get this error on Linux and provide code to reproduce.
