### ISSUE TITLE
Not suitable for Windows

### ISSUE THREAD

**Issue by AlexeiDimitriCampos** [webfp/tor-browser-selenium#212]
In Windows environment, this library keeps using POSIX binary format for executable (firefox instead of firefox.exe in Windows)

Result:
File "%AppData%\Python\Python312\site-packages\tbselenium\tbdriver.py", line 55, in __init__
    self.setup_tbb_paths(tbb_path, tbb_fx_binary_path,
  File "%AppData%\Python\Python312\site-packages\tbselenium\tbdriver.py", line 178, in setup_tbb_paths
    raise TBDriverPathError("Invalid Firefox binary %s"
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary %OneDrive%\Downloads\etc\Tor Browser\Browser\Browser\firefox

**Comment by gunesacar** [comment]
Unfortunately Windows is not supported.

See, https://github.com/webfp/tor-browser-selenium?tab=readme-ov-file#%EF%B8%8F-compatibility
> Warning: Windows and macOS are not supported.
