### ISSUE TITLE
New release for Tor Browser 14.0 support?

### ISSUE THREAD

**Issue by legoktm** [webfp/tor-browser-selenium#216]
Hi, thanks for maintaining this project :)

Could a new release be issued for Tor Browser 14.0 support? Specifically https://github.com/webfp/tor-browser-selenium/commit/2f9b066ead8a333e6834e4ea408b85b688afab18; for now we've monkey patched it into SecureDrop (https://github.com/freedomofpress/securedrop/commit/74ff170d45b13c02b22c5bf838e6c8c1d22c5dc5).

**Comment by gunesacar** [comment]
Thanks for the heads up. Should have made a release sooner.
Here is the new release: https://pypi.org/project/tbselenium/0.9.0/
Thanks for your work on SecureDrop as well.
