### ISSUE TITLE
Submit a package to PyPi

### ISSUE THREAD

**Issue by fowlslegs** [webfp/tor-browser-selenium#59]
You should consider shipping this as wheel via PyPi. It would be easier to use as a dependency for people and there are no real alternatives for those wishing to drive Tor Browser with a Python module.

**Comment by gunesacar** [comment]
Thanks @fowlslegs, good call!
Will work on that next week.

**Comment by gunesacar** [comment]
Here we go: https://pypi.python.org/pypi/tbselenium
