### ISSUE TITLE
Reduce test fragility

### ISSUE THREAD

**Issue by gunesacar** [webfp/tor-browser-selenium#6]
In majority of the tests, we load web pages over Tor network, which is not the most reliable transport. 

We should look for ways to make tests more resilient, such as rerunning tests when the failure is due to the network.

**Comment by gunesacar** [comment]
In https://github.com/webfp/tor-browser-selenium/commit/bf9879c169a17c80431d4c0b71084197cbce911a we added `load_url_ensure` method to retry if we can't load a URL. Also when the TorBrowserDriver init fails in TBDriverTest, we try again if it fails.

There's room for improvement but we can close this issue until we hit to a test failure.

**Comment by fowlslegs** [comment]
Maybe consider using stem to ensure retries happen over a different circuit?
