### ISSUE TITLE
Expose Tor bootstrap status/errors

### ISSUE THREAD

**Issue by gunesacar** [webfp/tor-browser-selenium#66]
When tor-browser-selenium is asked to start a Tor process and Tor cannot bootstrap, we get a [cryptic error from Selenium](https://github.com/webfp/tor-browser-selenium/issues/62):

`Can't load the profile. Profile Dir: /tmp/tmpxyz/webdriver-py-profilecopy If you specified a log_file in the FirefoxBinary constructor, check it for details`

@mjuarezm proposed that it could be useful to expose Tor bootstrap errors and/or status to callers.

**Comment by gunesacar** [comment]
I guess we can get the bootstrap status if `tbb_log_file` is available. But this argument is optional and no logging is done by default.

Perhaps we could use Stem to check the bootstrapping status, but adding a dependency is not preferred. This problem relates to cases where we don't use Stem but Tor Browser's `tor-launcher` does the bootstrapping.

**Comment by mccbala** [comment]
*bump*

**Comment by gunesacar** [comment]
With the latest (v0.4.1) update, `tbselenium` only uses external running `tor`. This issue is not relevant anymore, closing.
