### ISSUE TITLE
Can't read cookies

### ISSUE THREAD

**Issue by tkell** [webfp/tor-browser-selenium#79]
Hello!

I'm working on some stuff for SecureDrop, and it looks like maybe `tbselenium` can't read cookies, using `driver.get_cookies()`.  

I can _set_ cookies using `driver.add_cookies()`, and read them back - but when I see a Cookie header in tcpdump, I can't read the cookie in question. 

This could well be a problem with the test setup for SecureDrop - I don't have a minimal example, but I'll work on one. 

Thanks!

**Comment by tkell** [comment]
Example using Twitter login:

```
from tbselenium.tbdriver import TorBrowserDriver

pref_dict = {'network.proxy.no_proxies_on': '.twitter.com'}
with TorBrowserDriver("/opt/tbb/tor-browser_en-US/", pref_dict=pref_dict) as driver:
    driver.implicitly_wait(5)

    driver.get('https://twitter.com/login')
    username_field = driver.find_element_by_css_selector('input[class="js-username-field email-input js-initial-focus"]')
    username_field.send_keys('<TWITTER_USERNAME>')
    password_field = driver.find_element_by_css_selector('input[class="js-password-field"]')
    password_field.send_keys('<TWITTER_PASSWORD>')

    submit_button = driver.find_element_by_css_selector('button[class="submit btn primary-btn"]')
    submit_button.click()

    print driver.current_url
    print driver.get_cookies()
```

This outputs:
```
https://twitter.com/
[]
```

**Comment by gunesacar** [comment]
Thanks for reporting.

I tried with vanilla FirefoxDriver and get the same result (no cookies).
Also, reading https://github.com/robotframework/Selenium2Library/issues/177, I'm thinking that this may be a FirefoxDriver issue.

If that's compatible with what you're doing, you can disable PBM to access cookies.
Just add `"browser.privatebrowsing.autostart": False` to the `pref_dict` you have.
(Idea from https://github.com/robotframework/Selenium2Library/issues/177#issuecomment-37808376)

Disabling PBM may have side effects like storing things on the disk, please make sure it's OK for your case.

You can also use `driver.execute_script("return document.cookie")`, but `httponly` cookies will be missing in the list.

**Comment by tkell** [comment]
That config fixes it, 10,000 thanks!

Feel free to close this issue – I'll circle back with SecureDrop people to see if that's an acceptable bit of config to have in the tests.

**Comment by gunesacar** [comment]
I'm glad it worked. Maybe I should add a note about this in the troubleshooting section.

Thanks again for reporting.

**Comment by kushaldas** [comment]
Note: `"browser.privatebrowsing.autostart": False` works when working against 127.0.0.1 address, but not with the onion addresses. Could not find an way to get the cookies.

**Comment by gunesacar** [comment]
I could print the cookies on `http://www.propub3r6espa33w.onion/` using the following code: https://gist.github.com/gunesacar/0e0acfa8d71deffe6c45ccd29b8247f1

I run the following...:
`python cookie_check.py /path/to/tor-browser_en-US/ https://www.propub3r6espa33w.onion/`

...it prints (along with a ton of other debug messages from Firefox):
```
Finished loading https://www.propub3r6espa33w.onion/
Cookies: pp-tracking={"pageCount":0}; __gads=ID=5b2f86bbd40732dd:T=1517883426:S=ALNI_Mb57Tl8YkAq9jenlcBbufsbX9yLJQ```
