### ISSUE TITLE
How to authenticate tor controller using password

### ISSUE THREAD

**Issue by Zorgatone** [webfp/tor-browser-selenium#82]
When using `TorBrowserDriver(tor_cfg=cm.USE_RUNNING_TOR)` can it connect to the tor process, when a password is set for the controller connection?
If yes, how should i pass the password for the authentication to the `TorBrowserDriver()`?

**Comment by fowlslegs** [comment]
Do you want Tor Browser itself to authenticate to the control port or do you just want to be able to programmatically send the control port commands? I imagine in most scenarios you're automating the browser you'd want the latter. I believe the only control port command Tor Browser will send is NEWNYM and that is when you click "New Identity" in the Torbutton extension menu. You could do the same using `stem`.

**Comment by mjuarezm** [comment]
TorBrowserDriver does not connect to the Tor controller. As @fowlslegs mentioned, you need to use `stem` for that. Check this example: [`stem_adv.py`](https://github.com/webfp/tor-browser-selenium/blob/master/examples/stem_adv.py#L45). It uses the stem's `authenticate` [method](https://stem.torproject.org/api/connection.html#stem.connection.authenticate) to which you can pass user and password.

**Comment by fowlslegs** [comment]
I would use `getpass` if you want to interactively prompt for a password each time. Otherwise, setting `CookieAuth 1` in your `torrc` is easier than using a password (alternatively you can not modify your torrc and instead pass a `config` keyword dict to `stem.process.launch_tor_with_config` with that option).

**Comment by Zorgatone** [comment]
I'm already using stem with authentication to send commands programmatically.
I'm just wondering if I need to tell the Tor Browser the password when connecting to Tor when configured with a control password

**Comment by mjuarezm** [comment]
You can set a password for the Tor controller by setting the [HashedControlPassword](https://www.torproject.org/docs/tor-manual.html.en#HashedControlPassword) option in the torrc that the `TorBrowserDriver` will use. Again, you can set that option grammatically by making use of stem (see the [example](https://github.com/webfp/tor-browser-selenium/blob/ef5ba4975ec899a1ecccfaaca82e2df3d982a58a/examples/stem_adv.py#L42)).

**Comment by Zorgatone** [comment]
I'm telling you, that's what I'm already doing. You didn't get what I'm asking.

I start a tor process using stem, and setting the option programmatically using steam (not torrc), and when I connect to the controller (also using stem and HashedControlPassword) I am authenticating correctly.

Now I want to run the tor **browser** and connecting it to that tor process (Socks doesn't need password, I know that), but I was wondering if I also need to tell the Tor browser (and specifically Tor **button**) the password for the controller. Probably I don't really need to, as I'm sending commands only using stem

**Comment by Zorgatone** [comment]
Using `TorBrowserDriver(tor_cfg=cm.USE_RUNNING_TOR)` will be enough, or is there a `password` parameter to it?

**Comment by mjuarezm** [comment]
Yes, that's should be enough. The TorBrowserDriver does not talk to the Tor controller.

**Comment by fowlslegs** [comment]
> I'm just wondering if I need to tell the Tor Browser the password when connecting to Tor when configured with a control password

No. That's not necessary unless you plan on driving Selenium to click the TB UI buttons that would send control port commands, such as "New Identity." Since there's no point in doing such a thing when you can send the same command with `stem` programmatically, you should be able to just use it as a socks proxy without authenticating to the control port. The only use I could see for authenticating is if you were trying to functionally test the Tor Browser itself.

**Comment by Zorgatone** [comment]
Oh, I see. Ok.
Thanks!
