### ISSUE TITLE
WebDriverException: Can't load the profile. 

### ISSUE THREAD

**Issue by Waffleboy** [webfp/tor-browser-selenium#83]
WebDriverException: Can't load the profile. Profile Dir: /tmp/tmp_rzsi126/webdriver-py-profilecopy If you specified a log_file in the FirefoxBinary constructor, check it for details.

This occurs after i do:
```
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/storage/programfiles/tor-browser_en-US") as driver:
    driver.get('www.reddit.com')
```
Any idea on how to solve this? :)

**Comment by gunesacar** [comment]
Thanks for the report!

Can you tell me which version of the Tor Browser Bundle and selenium are you using?

The latest versions of both are not supported. See the `Compatibility` section in
https://github.com/webfp/tor-browser-selenium/blob/master/README.md

**Comment by Waffleboy** [comment]
Hey thanks for your quick reply! :)

Ah I'm using Tor browser 7.0.2 and selenium '2.53.6'

I have been searching for quite a while now for v 6.5.1 but can't seem to have any luck. All the repositories dont have it, and I cant find it via google too for some reason. Would you happen to have any idea how would I get this working?

**Comment by gunesacar** [comment]
You can download it at: https://archive.torproject.org/tor-package-archive/torbrowser/6.5.1/
