### ISSUE TITLE
Unable to use bridges other than obfs4

### ISSUE THREAD

**Issue by mccbala** [webfp/tor-browser-selenium#85]
The browser always initializes with obfs4 bridge when opened through the library. This happens even after I change it to any other bridge like meek-amazon and obfs4 takes long time to open. 

Directly opening the browser takes the saved settings but when opened with `tbselenium`, the torrc file `/home/olam/tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc` is being overwritten.

Tor Bundle Version: 6.5.1

**Comment by gunesacar** [comment]
You can use Firefox prefs to control the pluggable transport (PT) that is being used by `tbselenium`.

To find the relevant prefs, open `about:config` with Tor Browser (doesn't have to be via `tbselenium`). Enable the PT that you want to use. Firefox hints the changed prefs by making them bold.

Then pass the pref using the `pref_dict` argument during the initialization of TorBrowserDriver.

I'll create an example to show how to pick the PT that you want but it may take a few days.

**Comment by gunesacar** [comment]
Please see the newly added example and tests that makes use of different bridge types.
