### ISSUE TITLE
Tor Launches But Won't Get Page

### ISSUE THREAD

**Issue by ss32** [webfp/tor-browser-selenium#92]
I'm able to get the Tor browser to launch but sending the get command does nothing.  I have checked that I am able to use Tor outside of calling it via Selenium and it works fine.  If I wait long enough I get a connection refused message

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/tor-browser-selenium/tbselenium/tbdriver.py", line 57, in __init__
    log_path=tbb_logfile_path)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused`

Python 3.5.2, Selenium 3.8, Gecko 0.17.0
Tor 7.0.10, Linux Mint 18.1 (Ubuntu 16.04)

**Comment by gunesacar** [comment]
Thanks for reporting the issue, but I cannot reproduce this error. Could you please run the tests on the system you get this error and let me know if anything fails?

You need to cd into `tbselenium/test` and run `py.test`. You may need to install the python packages in https://github.com/webfp/tor-browser-selenium/blob/master/requirements-dev.txt

Also, it would be very helpful if you could provide the code that causes this error.

**Comment by ss32** [comment]
Which test would you like for me to run?  In `tbselenium/test` I have

    conftest.py      
    test_bundled_fonts.py   
    test_security_slider.py
    fixtures.py      
    test_context_switch.py  
    test_stem.py
    __init__.py      
    test_data               
    test_tbdriver.py
    __pycache__      
    test_env.py            
    test_tor.py
    test_addons.py  
    test_exceptions.py     
    test_utils.py
    test_bridge.py  
    test_js_disable.py
    test_browser.py  
    test_screenshot.py
And the code that is causing the error is the example listed in the Readme:

    from tbselenium.tbdriver import TorBrowserDriver
    with TorBrowserDriver("/home/user/tor-browser_en-US") as driver:
        driver.get('https://check.torproject.org')`

**Comment by gunesacar** [comment]
All the tests please. If you follow the instructions in my comment pytest will discover and run the tests automatically. Alternatively, you can follow the instructions given in the README: https://github.com/webfp/tor-browser-selenium#test-and-development

Missing -r flag is added, thanks for the heads up!

**Comment by ss32** [comment]
Got it.  It generated a 480MB text file, but I'm assuming the relevant portion is up top...


    ============================= test session starts ==============================
    platform linux -- Python 3.5.2, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
    rootdir: /home/scott/tor-browser-selenium, inifile:
    plugins: cov-2.5.1
    collected 51 items
    
    test_addons.py FFFF                                                      [  7%]
    test_bridge.py FEFEFEFEFE                                                [ 27%]
    test_browser.py EsEE                                                     [ 35%]
    test_bundled_fonts.py sssss                                              [ 45%]
    test_context_switch.py F                                                 [ 47%]
    test_env.py .                                                            [ 49%]
    test_exceptions.py .F...........                                         [ 74%]
    test_js_disable.py F                                                     [ 76%]
    test_screenshot.py EEE                                                   [ 82%]
    test_security_slider.py FF                                               [ 86%]
    test_stem.py EE                                                          [ 90%]
    test_tbdriver.py FFFFF                                                   [100%]F [101%]
    F                                                                        [103%]
    test_tor.py F                                                            [105%]
    test_utils.py ..
    
    ==================================== ERRORS ====================================
     ERROR at teardown of TBDriverBridgeTest.test_should_load_check_tpo_via_fte_bridge 
    
    self = <tbselenium.test.test_bridge.TBDriverBridgeTest testMethod=test_should_load_check_tpo_via_fte_bridge>
    
        def tearDown(self):
    >       self.tb_driver.quit()
    E       AttributeError: 'TBDriverBridgeTest' object has no attribute 'tb_driver'
    
    ../../tor-browser-selenium/tbselenium/test/test_bridge.py:13: AttributeError
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused

**Comment by gunesacar** [comment]
OK, it seems something goes wrong with the initialization. Most of the time this is due to missing libraries or other software that tbselenium depends on.

I'll need the tracebacks from the logs to understand the cause.

I don't need the whole 480MB, but if you can share from the beginning to the 5th (or so) occurrence of the `Captured stdout call`, it'd help a lot. That will give the details for the first five tests.

The logs may contain your user name, feel free to remove it or any other info that you are not comfortable sharing.

**Comment by ss32** [comment]
I printed the first 15 lines after the stdout call, let me know if you need more


    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343908304	geckodriver	INFO	geckodriver 0.19.1
    1512343908307	geckodriver	INFO	Listening on 127.0.0.1:38619
    1512343909829	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.68RV5P15xhYc"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343970168	geckodriver	INFO	geckodriver 0.19.1
    1512343970170	geckodriver	INFO	Listening on 127.0.0.1:45945
    1512343971697	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.OMKsuKshc8do"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344032044	geckodriver	INFO	geckodriver 0.19.1
    1512344032048	geckodriver	INFO	Listening on 127.0.0.1:56477
    1512344033576	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.IvJCUjWWH7rY"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344093916	geckodriver	INFO	geckodriver 0.19.1
    1512344093919	geckodriver	INFO	Listening on 127.0.0.1:34647
    1512344095443	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.iOC2LQn8uHob"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344155771	geckodriver	INFO	geckodriver 0.19.1
    1512344155774	geckodriver	INFO	Listening on 127.0.0.1:57351
    1512344157312	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.XrlcfzAzIKNu"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ---------------------------- Captured stdout setup -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344217660	geckodriver	INFO	geckodriver 0.19.1
    1512344217665	geckodriver	INFO	Listening on 127.0.0.1:53655
    1512344219186	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.5lLHbfNI4Alp"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ---------------------------- Captured stdout setup -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344465510	geckodriver	INFO	geckodriver 0.19.1
    1512344465513	geckodriver	INFO	Listening on 127.0.0.1:36737
    1512344467044	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.npasJ6OUhhAl"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ---------------------------- Captured stdout setup -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344659439	geckodriver	INFO	geckodriver 0.19.1
    1512344659442	geckodriver	INFO	Listening on 127.0.0.1:42631
    1512344660952	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.O9NoThHsXHq7"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343660776	geckodriver	INFO	geckodriver 0.19.1
    1512343660780	geckodriver	INFO	Listening on 127.0.0.1:41159
    1512343662293	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.9HHgZRYiBBJE"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343722679	geckodriver	INFO	geckodriver 0.19.1
    1512343722681	geckodriver	INFO	Listening on 127.0.0.1:46885
    1512343724219	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.8S5IifHScsrr"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343784571	geckodriver	INFO	geckodriver 0.19.1
    1512343784573	geckodriver	INFO	Listening on 127.0.0.1:37901
    1512343786101	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.YE2dEphoBINh"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343846458	geckodriver	INFO	geckodriver 0.19.1
    1512343846462	geckodriver	INFO	Listening on 127.0.0.1:54907
    1512343847987	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.FL8J73CFGFFl"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343908304	geckodriver	INFO	geckodriver 0.19.1
    1512343908307	geckodriver	INFO	Listening on 127.0.0.1:38619
    1512343909829	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.68RV5P15xhYc"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512343970168	geckodriver	INFO	geckodriver 0.19.1
    1512343970170	geckodriver	INFO	Listening on 127.0.0.1:45945
    1512343971697	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.OMKsuKshc8do"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344032044	geckodriver	INFO	geckodriver 0.19.1
    1512344032048	geckodriver	INFO	Listening on 127.0.0.1:56477
    1512344033576	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.IvJCUjWWH7rY"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344093916	geckodriver	INFO	geckodriver 0.19.1
    1512344093919	geckodriver	INFO	Listening on 127.0.0.1:34647
    1512344095443	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.iOC2LQn8uHob"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344155771	geckodriver	INFO	geckodriver 0.19.1
    1512344155774	geckodriver	INFO	Listening on 127.0.0.1:57351
    1512344157312	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.XrlcfzAzIKNu"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344279723	geckodriver	INFO	geckodriver 0.19.1
    1512344279726	geckodriver	INFO	Listening on 127.0.0.1:35207
    1512344281255	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.YTCA6mcdl1WN"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344341622	geckodriver	INFO	geckodriver 0.19.1
    1512344341626	geckodriver	INFO	Listening on 127.0.0.1:42871
    1512344343157	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.eFdz49AoSNSu"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344403660	geckodriver	INFO	geckodriver 0.19.1
    1512344403663	geckodriver	INFO	Listening on 127.0.0.1:38909
    1512344405186	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.RruKmIWvmpLv"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344527532	geckodriver	INFO	geckodriver 0.19.1
    1512344527536	geckodriver	INFO	Listening on 127.0.0.1:35287
    1512344529061	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ezeUvd8OC8on"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344589403	geckodriver	INFO	geckodriver 0.19.1
    1512344589406	geckodriver	INFO	Listening on 127.0.0.1:44653
    1512344590917	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.rCQYRhhjO7BU"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344721365	geckodriver	INFO	geckodriver 0.19.1
    1512344721368	geckodriver	INFO	Listening on 127.0.0.1:45073
    1512344722876	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.o0pQ7A5w2c0B"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344783203	geckodriver	INFO	geckodriver 0.19.1
    1512344783207	geckodriver	INFO	Listening on 127.0.0.1:37273
    1512344784739	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.BF71WBCwwrbw"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344845090	geckodriver	INFO	geckodriver 0.19.1
    1512344845093	geckodriver	INFO	Listening on 127.0.0.1:43471
    1512344846601	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.j8XeIE4JsX8Y"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344906922	geckodriver	INFO	geckodriver 0.19.1
    1512344906925	geckodriver	INFO	Listening on 127.0.0.1:43495
    1512344908433	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.tT9R7KMFUpBm"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512344968757	geckodriver	INFO	geckodriver 0.19.1
    1512344968761	geckodriver	INFO	Listening on 127.0.0.1:45041
    1512344970268	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.k3kLEVP0hdOS"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028
    ----------------------------- Captured stdout call -----------------------------
    
    TBDriver init error. Attempt 1 Message: connection refused
    
    TB logs:
    1512345030588	geckodriver	INFO	geckodriver 0.19.1
    1512345030591	geckodriver	INFO	Listening on 127.0.0.1:49227
    1512345032111	mozrunner::runner	INFO	Running command: "/home/user/tor-browser_en-US/Browser/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.flySLfYJR6th"
    Unable to update the static FcBlanks: 0x0600
    Unable to update the static FcBlanks: 0x0601
    Unable to update the static FcBlanks: 0x0602
    Unable to update the static FcBlanks: 0x0603
    Unable to update the static FcBlanks: 0x06dd
    Unable to update the static FcBlanks: 0x070f
    Unable to update the static FcBlanks: 0x2028

**Comment by gunesacar** [comment]
Oh, it looks like you have the wrong `geckodriver` version in your PATH.  `which geckodriver` command will give you `geckodriver`'s location, overwrite the existing binary with that of 0.17.0.

When you are done, `geckodriver --version` should return 0.17.0.
