### ISSUE TITLE
TBB_PATH` can't be found

### ISSUE THREAD

**Issue by YODAWGAADADWA** [webfp/tor-browser-selenium#96]
raise TBTestEnvVarError("Environment variable `TBB_PATH` can't be found.")
tbselenium.exceptions.TBTestEnvVarError: Environment variable `TBB_PATH` can't be found.
using windows btw
I try: 
C:\Users\D1\Desktop\Tor Browser\Start Tor Browser.lnk

C:\Users\D1\Desktop\Tor Browser\Browser\firefox.exe

C:\\Users\\D1\\Desktop\\Tor Browser\\Browser\\TorBrowser\\Tor\\tor.exe

What am I missing here?

from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("C:/Users/D1/Desktop/Tor Browser/Browser/orBrowser/Tor/tor.exe") as driver:
    driver.get('https://check.torproject.org')

**Comment by gunesacar** [comment]
Thanks for reporting, but Windows is not supported. I [changed](https://github.com/webfp/tor-browser-selenium/commit/01fec0530214082db5f6d145430d592d38e571d1) the README to clarify.
You may try running tor-browser-selenium in a Linux VM.
