### ISSUE TITLE
Environment variable `TBB_PATH` can't be found.

### ISSUE THREAD

**Issue by MislavSag** [webfp/tor-browser-selenium#98]
Hi,

I have installed tbselenium, geckodriver and TBB as required, but when I try first basic usage:
```
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("C:/Users/msagovac/Desktop/Tor Browser") as driver:
    driver.get('https://check.torproject.org')
```
I got an error:
`Environment variable `TBB_PATH` can't be found.`
I am not sure what should be TorBrowserBundle path. Try many alternatives.

I ma using Python 3 on Windows

**Comment by gunesacar** [comment]
Sorry, Windows is not supported: https://github.com/webfp/tor-browser-selenium#compatibility

**Comment by StigP1337** [comment]
Same error happens when you use Python 3 on Linux. I did the same steps as MislavSag and got the same error about missing TBB_PATH. I had to set TBB_PATH although it is ignored and the path supplied in the constructor is used.

**Comment by gunesacar** [comment]
Thanks @StigP1337. I think this was fixed in master, but didn't get into a release.

I just made a new release (v0.3.3). You shouldn't be getting this error after you update your `tbselenium` package.
