### ISSUE TITLE
The torrc file is missing and could not be created.

### ISSUE THREAD

**Issue by ApertureSecurity** [webfp/tor-browser-selenium#99]
Hello  receive this error upon launching tor through this. 

The torrc file is missing and could not be created.

When I manually run the torbrowser from command line it works fine Before I provide the massive amounts of logs I have , is this a known issue? Is there anything I can do?

Let me know if you want the runtime logs,

Thanks
I am just using the basic example on the site.

```
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/path/to/myBundle/") as driver:
    driver.get('https://check.torproject.org')
```

**Comment by XGoldenEggX** [comment]
I had same problem when adding browser to path, while my pycharm (python ide) was opened. 
Try to reopen IDE you working in.

**Comment by gunesacar** [comment]
@ApertureSecurity this is not a known problem.

Please try @XGoldenEggX's suggestion and if it doesn't work, please provide the TBB version, OS info, python version and the logs (after removing any potentially sensitive information).

This may be a file permission issue. Make sure the user has permission to write to the TBB folder.

To bypass this issue, you may use the system tor, i.e. tor process running on your system, instead of having tbselenium start the tor process. You'd need to pass `tor_cfg=cm.USE_RUNNING_TOR` argument to the TorBrowserDriver constructor.

**Comment by ApertureSecurity** [comment]
Ok . I will try this.

I was running in the terminal from atom ide. I think it will do the same in terminal.

I am on Linux a ubuntu dirivitive , i will try this and report my findings .

**Comment by ApertureSecurity** [comment]
Ok well it launches now but crashes after a certian point. Not sure why this happens though. 
```

Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=8.94902) [GFX1-]: Receive IPC close with rea
son=AbnormalShutdown
[Child 2862] WARNING: pipe error: Broken pipe: file /var/tmp/build/firefox-017a7ad9488d/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 68
5
[Child 2862] ###!!! ABORT: Aborting on channel error.: file /var/tmp/build/firefox-017a7ad9488d/ipc/glue/MessageChannel.cpp, line 2152
[Child 2862] ###!!! ABORT: Aborting on channel error.: file /var/tmp/build/firefox-017a7ad9488d/ipc/glue/MessageChannel.cpp, line 2152
Feb 23 20:19:58.000 [notice] Owning controller connection has closed -- exiting now.
Feb 23 20:19:58.000 [notice] Catching signal TERM, exiting cleanly.
```

**Comment by ApertureSecurity** [comment]
Ok let's see if I can get you these answers

Python 2.7.12
Files have RWX access in the correct directories. 

It loads and then dies here is a log dump of this that will alst 2 days.

https://expirebox.com/delete/5a9c394f45fda9aecf96787b729a1ff0.html

**Comment by gunesacar** [comment]
> Ok well it launches now but crashes after a certian point. Not sure why this happens though.

Does it crash seconds after launching, or minutes?

Sorry, I couldn't get the log dump in time. Feel free to email me the link if you do not prefer sharing the logs here: gunes@princeton.edu PGP key: https://pgp.mit.edu/pks/lookup?search=gunes%40princeton.edu&op=index

**Comment by digiboons** [comment]
It is the same for me as ApertureSecurity said.It crashed as soon as loaded page 
Thanks in advanve

**Comment by PierreSp** [comment]
Hello,

I do have the same problem as the other users (when I try to run the basic example I get the message The torrc file is missing and could not be created.)

I'm using python 3.6.5, the recent version of TBB(Tor Browser 7.5.5) and of tor-browser-selenium. 

After the torrc message it shut down because of a timeout, but before I get the following error message

```
1529257576300	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1529257576300	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1529257576400	addons.webextension.{73a6fe31-595d-460b-a920-fcc0f8843232}	WARN	Loading extension '{73a6fe31-595d-460b-a920-fcc0f8843232}': Reading manifest: Error processing permissions.1: Unknown permission "privacy"
1529257576400	addons.webextension.{73a6fe31-595d-460b-a920-fcc0f8843232}	WARN	Loading extension '{73a6fe31-595d-460b-a920-fcc0f8843232}': Reading manifest: Error processing permissions.4: Unknown permission "unlimitedStorage"
1529257576400	DeferredSave.extensions.json	DEBUG	Starting write
1529257576400	addons.webextension.https-everywhere-eff@eff.org	WARN	Loading extension 'https-everywhere-eff@eff.org': Reading manifest: Error processing devtools_page: An unexpected property was found in the WebExtension manifest.
1529257576400	addons.webextension.https-everywhere-eff@eff.org	WARN	Please specify whether you want browser_style or not in your browser_action options.
1529257576500	DeferredSave.extensions.json	DEBUG	Write succeeded
1529257584200	addons.xpi	DEBUG	Calling bootstrap method shutdown on {73a6fe31-595d-460b-a920-fcc0f8843232} version 5.1.8.5
1529257584200	addons.xpi	DEBUG	Calling bootstrap method shutdown on https-everywhere-eff@eff.org version 2018.6.13
1529257584200	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.10
JavaScript error: resource:///modules/BrowserUsageTelemetry.jsm, line 211: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]
1529257584300	addons.manager	DEBUG	shutdown
```

Using USE_RUNNING_TOR it shows the error: `TBDriverPortError: SOCKS port 9050 is not listening`
even though the tor browser is running :(

I also tried to set the path of the binary and profile, as I wasn't sure, whether it is the right one for linux, but that did not help, too. Does anybody found a solution already? Or can I help you with more logs / infos?


Thank you very much in advance!

**Comment by gunesacar** [comment]
Thanks for the report.

> Using USE_RUNNING_TOR it shows the error: TBDriverPortError: SOCKS port 9050 is not listening
> even though the tor browser is running :(

`USE_RUNNING_TOR` requires _tor_ to be running (not necessarily Tor Browser). This is the one you install by running `apt get install tor`.

You also need to make sure `tor` is listening on port 9050. The output of `sudo netstat -peanut | grep -w tor` should include:
```
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      0          xxxx      1212/tor            
```

But, the simplest code example doesn't need system tor to be running. Say, you extracted the Tor Browser Bundle into `/tmp/` directory. If you use the default (English) bundle, it'll be extracted to `/tmp/tor-browser_en-US/`. Then the following code should work.
```
from time import sleep
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/tmp/tor-browser_en-US/") as driver:
    driver.get('https://check.torproject.org')
    sleep(10)
```
